CREATE TABLE `t_menu_desktop`
(
    `id`                   varchar(32) NOT NULL COMMENT 'id',
    `name`                 varchar(50)  DEFAULT NULL COMMENT '菜单名称',
    `sort`                 int          DEFAULT NULL COMMENT '排序',
    `parent_id`            varchar(32)  DEFAULT NULL COMMENT '父级菜单id',
    `menu_layout`          varchar(100) DEFAULT NULL COMMENT 'title标题栏;top顶部工具栏;bottom底部工具栏;menuBox工具箱;context右键菜单',
    `type`                 varchar(100) DEFAULT NULL COMMENT '菜单类型（scheme、drawing、assembly）',
    `command_params`       varchar(255) DEFAULT NULL COMMENT '命令id对应的参数值',
    `icon_active`          varchar(255) DEFAULT NULL COMMENT '激活态菜单icon',
    `icon_normal`          varchar(255) DEFAULT NULL COMMENT '正常态菜单icon',
    `icon_selected`        varchar(255) DEFAULT NULL COMMENT '选中态菜单icon',
    `level`                varchar(100) DEFAULT NULL COMMENT '菜单级别。\r\n\r\nproject：项目级，以按钮形式存在，切换项目时会切换。 \r\n\r\ncommon：公用级，以按钮形式存在，所有项目都会有，不会切换\r\n\r\nmenu：按钮级，放置在面板或者工具条上的菜单，以按钮形式存在\r\n\r\npop：弹出级，归属于menu下；目前只支持级联1层，即pop层的菜单不允许再有子菜单',
    `separater`            tinyint      DEFAULT NULL COMMENT '是否在菜单后添加分隔符，只支持顶部和底部工具栏，1是 0 否',
    `show`                 tinyint      DEFAULT NULL COMMENT '是否默认显示，1是0否，默认0',
    `tool_name`            varchar(255) DEFAULT NULL COMMENT '菜单所属tool（cube定义）',
    `tool_tip`             varchar(255) DEFAULT NULL COMMENT 'hover提示',
    `belongs`              varchar(255) DEFAULT NULL COMMENT '菜单归属（名称由local定义）比如平面视图、草图、布局',
    `available`            tinyint      DEFAULT NULL COMMENT '是否可用。1是0否',
    `group`                varchar(255) DEFAULT NULL COMMENT '菜单所属分组（此为web保留字段，目前本地端暂无分组）',
    `command_id`           int          DEFAULT NULL COMMENT '命令id',
    `short_cut`            varchar(255) DEFAULT NULL COMMENT '快捷键',
    `variable_name`        varchar(255) DEFAULT NULL COMMENT '根据配置自动生成代码时的变量名称，全局唯一即可，建议同菜单名称关联',
    `tool_button_style`    varchar(255) DEFAULT NULL COMMENT '菜单的样式\r\n\r\nToolButtonTextUnderIcon：显示icon + 名称\r\nToolButtonIconOnly：只显示icon',
    `callback`             varchar(255) DEFAULT NULL COMMENT '菜单激活时的回调函数（由C++开发提供），同commandId互斥，且优先级比commandId高',
    `brother_tools`        text COMMENT '显示亲近的tool；进入tool 则显示菜单；英文逗号分割',
    `exclude_tools`        text COMMENT '	显示排斥的tool；进入tool 则隐藏菜单；英文逗号分割',
    `checkable`            tinyint      DEFAULT NULL COMMENT '点击时是否高亮(0-不高亮；1-高亮)',
    `enable`               tinyint      DEFAULT NULL COMMENT '是否可点击 1是0否',
    `select_brother_tools` text COMMENT '选择显示的tool，选中对象 显示菜单；英文逗号分割',
    `select_exclude_tools` text COMMENT '选择排斥的tool，选中对象 隐藏菜单；英文逗号分割',
    `disable_tools`        text COMMENT '禁用菜单的tool，进入tool 则禁用菜单；英文逗号分割',
    `enable_tools`         text COMMENT '启用菜单的tool，进入tool 则启用菜单；英文逗号分割',
    `select_disable_tools` text COMMENT '选择禁用的tool，选中对象 禁用菜单；英文逗号分割',
    `select_enable_tools`  text COMMENT '选择启用的tool，选中对象 启用菜单；英文逗号分割',
    `has_secondary`        tinyint      DEFAULT NULL COMMENT '是否存在二级子菜单；1是0否；为true时才会解析confirmTools和confirmButtons',
    `confirm_tools`        text COMMENT '存在确认按钮的tool；用于二级子菜单，同confirmButtons一起使用；英文逗号分割',
    `confirm_buttons`      text COMMENT '二级子菜单的确认按钮列表',
    PRIMARY KEY (`id`),
    KEY `idx_type_layout` (`type`, `menu_layout`)
) COMMENT ='本地端菜单表';
